Upgrade Python in devcontainer to 3.10 and improve it

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -1,21 +1,13 @@
-FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9
+FROM python:3.10
 
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+# Ensure RUN fails if any command fails
+SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]
 
-# Uninstall pre-installed formatting and linting tools
-# They would conflict with our pinned versions
-RUN pipx uninstall black
-RUN pipx uninstall flake8
-RUN pipx uninstall pydocstyle
-RUN pipx uninstall pycodestyle
-RUN pipx uninstall mypy
-RUN pipx uninstall pylint
-
-RUN \
-    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
-    && apt-get update \
-    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-        # Additional library needed by some tests and accordingly by VScode Tests Discovery
+# Install apt-get dependencies
+RUN export DEBIAN_FRONTEND=noninteractive; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+        # Additional library needed by some tests and accordingly by VScode Tests Discovery \
         bluez \
         libudev-dev \
         libavformat-dev \
@@ -31,24 +23,23 @@ RUN \
         libxml2 \
         git \
         cmake \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
+        # Needed by the stream component \
+        ffmpeg; \
+    rm -rf /var/lib/apt/lists/*
 
-WORKDIR /usr/src
+# Upgrade pip
+RUN pip3 install --upgrade pip
 
 # Setup hass-release
-RUN git clone --depth 1 https://github.com/home-assistant/hass-release \
-    && pip3 install -e hass-release/
-
-WORKDIR /workspaces
+WORKDIR /usr/src/hass-release
+RUN git clone --depth 1 https://github.com/home-assistant/hass-release . \
+    && pip3 install -e .
 
 # Install Python dependencies from requirements
-COPY requirements.txt ./
+WORKDIR /usr/src/homeassistant
+COPY requirements.txt .
 COPY homeassistant/package_constraints.txt homeassistant/package_constraints.txt
 RUN pip3 install -r requirements.txt --use-deprecated=legacy-resolver
 COPY requirements_test.txt requirements_test_pre_commit.txt ./
 RUN pip3 install -r requirements_test.txt --use-deprecated=legacy-resolver
 RUN rm -rf requirements.txt requirements_test.txt requirements_test_pre_commit.txt homeassistant/
-
-# Set the default shell to bash instead of sh
-ENV SHELL /bin/bash
