Attempt to auto install node for frontend dev

diff --git a/script/bootstrap_frontend b/script/bootstrap_frontend
--- a/script/bootstrap_frontend
+++ b/script/bootstrap_frontend
@@ -11,6 +11,19 @@ echo "Bootstrapping frontend..."
 git submodule update
 cd homeassistant/components/frontend/www_static/home-assistant-polymer
 
+# Check if npm is installed
+if ! command -v npm >/dev/null 2>&1 ; then
+    if python -c 'import sys; exit (0 if hasattr(sys, "real_prefix") else 1)' ; then
+        # In a virtual environment, attempt npm install
+        echo "Installing npm in virtual environment..."
+        pip install nodeenv
+        nodeenv --python-virtualenv
+    else
+        echo "npm is required for frontend development."
+        exit 1
+    fi
+fi
+
 # Install node modules
 npm install
 
