Improve development workflow in docker (#5079)
* Allow bower install of frontend components as root. Needed for frontend development in docker since everything runs as root in the docker image.

* Improve development workflow in docker

* Use LANG=C.UTF-8 in tox. Fixes installation of libraries with UTF-8 in it's readme.

* Install mysqlclient psycopg2 uvloop after requirements_all.txt again, but with a --no-cache-dir this time. Allows bootstrap_frontend to be executed in a different path like the other scripts.

diff --git a/script/bootstrap_server b/script/bootstrap_server
--- a/script/bootstrap_server
+++ b/script/bootstrap_server
@@ -1,3 +1,9 @@
+#!/bin/sh
+# Resolve all server dependencies that the application requires to run.
+
+# Stop on errors
+set -e
+
 cd "$(dirname "$0")/.."
 
 echo "Installing dependencies..."
