Update dirty script

diff --git a/script/check_dirty b/script/check_dirty
--- a/script/check_dirty
+++ b/script/check_dirty
@@ -1,2 +1,7 @@
 #!/bin/bash
-[[ -z $(git ls-files --others --exclude-standard) ]] || { echo -e '\n***** ERROR: Tests are leaving files behind. Please update the tests to avoid writing any files.\n'; exit 1; }
+[[ -z $(git ls-files --others --exclude-standard) ]] && exit 0
+
+echo -e '\n***** ERROR\nTests are leaving files behind. Please update the tests to avoid writing any files:'
+git ls-files --others --exclude-standard
+echo
+exit 1
