Detect and use min python version if found
When the min python version for Home Assistant changes, it can sometimes
cause unexpected breakeage for developers not using a dev container.
The source of the breakage is not always apparent. This is especially
true for users who have multiple Python versions on their system.

This patch reads the min version from the `pyproject.toml` file and then
tries to detect a `python` executable for that version (eg.
`python3.11`) and then uses that for the venv creation. If it cannot
find this, it will fall back to using `python3` as before.

Additionally, when `script/setup` is run, it will check the min python
version that was used in the venv to ensure the requirement is met. This
will help catch the cases where a user may only have an executable for
`python3` that may or may not point to a compatible verison of Python.

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -16,9 +16,24 @@ fi
 
 mkdir -p config
 
-if [ ! -n "$DEVCONTAINER" ] && [ ! -n "$VIRTUAL_ENV" ];then
-  python3 -m venv venv
+
+# Read min required python
+MIN_PYTHON="$(python3 -c 'import toml; print(".".join(toml.load(open("pyproject.toml"))["project"]["requires-python"].lstrip("=>").split(".")[:2]))')"
+
+if [ -z "$DEVCONTAINER" ] && [ -z "$VIRTUAL_ENV" ];then
+  # Try to use specific required python binary
+  PY3="python$MIN_PYTHON"
+  if ! hash "$PY3" > /dev/null ;then
+    PY3=python3
+  fi
+  $PY3 -m venv venv
   source venv/bin/activate
+fi
+
+# Check python version
+if ! python3 -c "import platform; exit(0) if tuple(int(v) for v in platform.python_version_tuple()) >= tuple(int(v) for v in '$MIN_PYTHON'.split('.')) else exit(1)" ;then
+  echo "ERROR: Min python version isn't being used. Make sure your version is greater than or equal to $MIN_PYTHON".
+  exit 1
 fi
 
 script/bootstrap
