black

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,7 +23,7 @@ env:
   CACHE_VERSION: 0
   PIP_CACHE_VERSION: 0
   HA_SHORT_VERSION: 2022.7
-  DEFAULT_PYTHON: "3.9.0"
+  DEFAULT_PYTHON: 3.9
   PRE_COMMIT_CACHE: ~/.cache/pre-commit
   PIP_CACHE: /tmp/pip-cache
   SQLALCHEMY_WARN_20: 1
@@ -165,7 +165,7 @@ jobs:
     timeout-minutes: 20
     strategy:
       matrix:
-        python-version: ["3.9.0", "3.10.0"]
+        python-version: ["3.9", "3.10"]
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v3.0.2
@@ -214,7 +214,7 @@ jobs:
         with:
           path: ${{ env.PRE_COMMIT_CACHE }}
           key: >-
-            ${{ runner.os }}-${{ steps.generate-pre-commit-key.outputs.pre-commit_cache_key }}
+            ${{ runner.os }}-${{ needs.info.outputs.pre-commit_cache_key }}
 
       - name: Install pre-commit dependencies
         if: steps.cache-precommit.outputs.cache-hit != 'true'
@@ -222,55 +222,55 @@ jobs:
           . venv/bin/activate
           pre-commit install-hooks
 
-  # lint-black:
-  #   name: Check black
-  #   runs-on: ubuntu-22.04
-  #   needs:
-  #     - changes
-  #     - prepare-base
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v3.0.2
-  #     - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-  #       uses: actions/setup-python@v4.0.0
-  #       id: python
-  #       with:
-  #         python-version: ${{ env.DEFAULT_PYTHON }}
-  #     - name: Restore base Python virtual environment
-  #       id: cache-venv
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: venv
-  #         key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
-  #           needs.prepare-base.outputs.python-key }}
-  #     - name: Fail job if Python cache restore failed
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       run: |
-  #         echo "Failed to restore Python virtual environment from cache"
-  #         exit 1
-  #     - name: Restore pre-commit environment from cache
-  #       id: cache-precommit
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: ${{ env.PRE_COMMIT_CACHE }}
-  #         key: ${{ runner.os }}-${{ needs.prepare-base.outputs.pre-commit-key }}
-  #     - name: Fail job if pre-commit cache restore failed
-  #       if: steps.cache-precommit.outputs.cache-hit != 'true'
-  #       run: |
-  #         echo "Failed to restore pre-commit environment from cache"
-  #         exit 1
-  #     - name: Run black (fully)
-  #       if: needs.changes.outputs.test_full_suite == 'true'
-  #       run: |
-  #         . venv/bin/activate
-  #         pre-commit run --hook-stage manual black --all-files --show-diff-on-failure
-  #     - name: Run black (partially)
-  #       if: needs.changes.outputs.test_full_suite == 'false'
-  #       shell: bash
-  #       run: |
-  #         . venv/bin/activate
-  #         shopt -s globstar
-  #         pre-commit run --hook-stage manual black --files {homeassistant,tests}/components/${{ needs.changes.outputs.integrations_glob }}/**/* --show-diff-on-failure
+  lint-black:
+    name: Check black
+    runs-on: ubuntu-22.04
+    needs:
+      - info
+      - prepare-base
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.0.2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v4.0.0
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v3.0.4
+        with:
+          path: venv
+          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
+            needs.info.outputs.python_cache_ke }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Restore pre-commit environment from cache
+        id: cache-precommit
+        uses: actions/cache@v3.0.4
+        with:
+          path: ${{ env.PRE_COMMIT_CACHE }}
+          key: ${{ runner.os }}-${{ needs.info.outputs.pre-commit_cache_key }}
+      - name: Fail job if pre-commit cache restore failed
+        if: steps.cache-precommit.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore pre-commit environment from cache"
+          exit 1
+      - name: Run black (fully)
+        if: needs.info.outputs.test_full_suite == 'true'
+        run: |
+          . venv/bin/activate
+          pre-commit run --hook-stage manual black --all-files --show-diff-on-failure
+      - name: Run black (partially)
+        if: needs.info.outputs.test_full_suite == 'false'
+        shell: bash
+        run: |
+          . venv/bin/activate
+          shopt -s globstar
+          pre-commit run --hook-stage manual black --files {homeassistant,tests}/components/${{ needs.info.outputs.integrations_glob }}/**/* --show-diff-on-failure
 
   # lint-flake8:
   #   name: Check flake8
