gen_requirements_all & hassfest

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -504,129 +504,69 @@ jobs:
           shopt -s globstar
           pre-commit run --hook-stage manual bandit --files {homeassistant,tests}/components/${{ needs.info.outputs.integrations_glob }}/**/* --show-diff-on-failure
 
-  # hassfest:
-  #   name: Check hassfest
-  #   runs-on: ubuntu-20.04
-  #   needs: prepare-tests
-  #   strategy:
-  #     matrix:
-  #       python-version: [3.9]
-  #   container: homeassistant/ci-azure:${{ matrix.python-version }}
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v3.0.2
-  #     - name: Restore full Python ${{ matrix.python-version }} virtual environment
-  #       id: cache-venv
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: venv
-  #         key: ${{ runner.os }}-${{ matrix.python-version }}-${{
-  #           needs.prepare-tests.outputs.python-key }}
-  #     - name: Fail job if Python cache restore failed
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       run: |
-  #         echo "Failed to restore Python virtual environment from cache"
-  #         exit 1
-  #     - name: Run hassfest
-  #       run: |
-  #         . venv/bin/activate
-  #         python -m script.hassfest --requirements --action validate
+  hassfest:
+    name: Check hassfest
+    runs-on: ubuntu-20.04
+    needs:
+      - info
+      - prepare-tests
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.0.2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v4.0.0
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore full Python ${{ env.DEFAULT_PYTHON }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v3.0.4
+        with:
+          path: venv
+          key: >-
+            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
+            needs.info.outputs.python_cache_key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run hassfest
+        run: |
+          . venv/bin/activate
+          python -m script.hassfest --requirements --action validate
 
-  # gen-requirements-all:
-  #   name: Check all requirements
-  #   runs-on: ubuntu-20.04
-  #   needs: prepare-base
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v3.0.2
-  #     - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-  #       uses: actions/setup-python@v4.0.0
-  #       id: python
-  #       with:
-  #         python-version: ${{ env.DEFAULT_PYTHON }}
-  #     - name: Restore base Python virtual environment
-  #       id: cache-venv
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: venv
-  #         key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
-  #           needs.prepare-base.outputs.python-key }}
-  #     - name: Fail job if Python cache restore failed
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       run: |
-  #         echo "Failed to restore Python virtual environment from cache"
-  #         exit 1
-  #     - name: Run gen_requirements_all.py
-  #       run: |
-  #         . venv/bin/activate
-  #         python -m script.gen_requirements_all validate
-
-  # prepare-tests:
-  #   name: Prepare tests for Python ${{ matrix.python-version }}
-  #   runs-on: ubuntu-20.04
-  #   timeout-minutes: 60
-  #   strategy:
-  #     matrix:
-  #       python-version: ["3.9", "3.10"]
-  #   outputs:
-  #     python-key: ${{ steps.generate-python-key.outputs.key }}
-  #   container: homeassistant/ci-azure:${{ matrix.python-version }}
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v3.0.2
-  #     - name: Generate partial Python venv restore key
-  #       id: generate-python-key
-  #       run: >-
-  #         echo "::set-output name=key::venv-${{ env.CACHE_VERSION }}-${{
-  #           hashFiles('requirements_test.txt') }}-${{
-  #           hashFiles('requirements_all.txt') }}-${{
-  #           hashFiles('homeassistant/package_constraints.txt') }}"
-  #     - name: Generate partial pip restore key
-  #       id: generate-pip-key
-  #       run: >-
-  #         echo "::set-output name=key::pip-${{ env.PIP_CACHE_VERSION }}-${{
-  #           env.HA_SHORT_VERSION }}-$(date -u '+%Y-%m-%dT%H:%M:%s')"
-  #     - name: Restore full Python ${{ matrix.python-version }} virtual environment
-  #       id: cache-venv
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: venv
-  #         key: >-
-  #           ${{ runner.os }}-${{ matrix.python-version }}-${{
-  #           steps.generate-python-key.outputs.key }}
-  #         # Temporary disabling the restore of environments when bumping
-  #         # a dependency. It seems that we are experiencing issues with
-  #         # restoring environments in GitHub Actions, although unclear why.
-  #         # First attempt: https://github.com/home-assistant/core/pull/62383
-  #         #
-  #         # restore-keys: |
-  #         #   ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('requirements_test.txt') }}-${{ hashFiles('requirements_all.txt') }}-
-  #         #   ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('requirements_test.txt') }}-
-  #         #   ${{ runner.os }}-${{ matrix.python-version }}-venv-${{ env.CACHE_VERSION }}-
-  #     - name: Restore pip wheel cache
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: ${{ env.PIP_CACHE }}
-  #         key: >-
-  #           ${{ runner.os }}-${{ matrix.python-version }}-${{
-  #           steps.generate-pip-key.outputs.key }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ env.PIP_CACHE_VERSION }}-${{ env.HA_SHORT_VERSION }}-
-  #     - name: Create full Python ${{ matrix.python-version }} virtual environment
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       run: |
-  #         # Temporary addition of cmake, needed to build some Python 3.9 packages
-  #         apt-get update
-  #         apt-get -y install cmake
-
-  #         python -m venv venv
-  #         . venv/bin/activate
-  #         python --version
-  #         pip install --cache-dir=$PIP_CACHE -U "pip>=21.0,<22.2" setuptools wheel
-  #         pip install --cache-dir=$PIP_CACHE -r requirements_all.txt --use-deprecated=legacy-resolver
-  #         pip install --cache-dir=$PIP_CACHE -r requirements_test.txt --use-deprecated=legacy-resolver
-  #         pip install -e .
+  gen-requirements-all:
+    name: Check all requirements
+    runs-on: ubuntu-20.04
+    needs:
+      - info
+      - prepare-base
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.0.2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v4.0.0
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v3.0.4
+        with:
+          path: venv
+          key: >-
+            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
+            needs.info.outputs.python_cache_key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run gen_requirements_all.py
+        run: |
+          . venv/bin/activate
+          python -m script.gen_requirements_all validate
 
   # pylint:
   #   name: Check pylint
