pytest

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -727,110 +727,110 @@ jobs:
   #         . venv/bin/activate
   #         ./script/pip_check $PIP_CACHE
 
-  # pytest:
-  #   runs-on: ubuntu-22.04
-  #   if: |
-  #     (github.event_name != 'push' || github.event.repository.full_name == 'home-assistant/core')
-  #     && github.event.inputs.lint-only != 'true'
-  #     && (needs.changes.outputs.test_full_suite == 'true' || needs.changes.outputs.tests_glob)
-  #   needs:
-  #     - changes
-  #     - gen-requirements-all
-  #     - hassfest
-  #     - lint-black
-  #     - lint-other
-  #     - lint-isort
-  #     - mypy
-  #     - prepare-tests
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       group: ${{ fromJson(needs.changes.outputs.test_groups) }}
-  #       python-version: ["3.9", "3.10"]
-  #   name: >-
-  #     Run tests Python ${{ matrix.python-version }} (${{ matrix.group }})
-  #   container: homeassistant/ci-azure:${{ matrix.python-version }}
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v3.0.2
-  #     - name: Restore full Python ${{ matrix.python-version }} virtual environment
-  #       id: cache-venv
-  #       uses: actions/cache@v3.0.4
-  #       with:
-  #         path: venv
-  #         key: ${{ runner.os }}-${{ matrix.python-version }}-${{
-  #           needs.prepare-tests.outputs.python-key }}
-  #     - name: Fail job if Python cache restore failed
-  #       if: steps.cache-venv.outputs.cache-hit != 'true'
-  #       run: |
-  #         echo "Failed to restore Python virtual environment from cache"
-  #         exit 1
-  #     - name: Register Python problem matcher
-  #       run: |
-  #         echo "::add-matcher::.github/workflows/matchers/python.json"
-  #     - name: Install Pytest Annotation plugin
-  #       run: |
-  #         . venv/bin/activate
-  #         # Ideally this should be part of our dependencies
-  #         # However this plugin is fairly new and doesn't run correctly
-  #         # on a non-GitHub environment.
-  #         pip install pytest-github-actions-annotate-failures==0.1.3
-  #     - name: Register pytest slow test problem matcher
-  #       run: |
-  #         echo "::add-matcher::.github/workflows/matchers/pytest-slow.json"
-  #     - name: Run pytest (fully)
-  #       if: needs.changes.outputs.test_full_suite == 'true'
-  #       timeout-minutes: 60
-  #       run: |
-  #         . venv/bin/activate
-  #         python --version
-  #         python3 -X dev -m pytest \
-  #           -qq \
-  #           --timeout=9 \
-  #           --durations=10 \
-  #           -n auto \
-  #           --dist=loadfile \
-  #           --test-group-count ${{ needs.changes.outputs.test_group_count }} \
-  #           --test-group=${{ matrix.group }} \
-  #           --cov="homeassistant" \
-  #           --cov-report=xml \
-  #           -o console_output_style=count \
-  #           -p no:sugar \
-  #           tests
-  #     - name: Run pytest (partially)
-  #       if: needs.changes.outputs.test_full_suite == 'false'
-  #       timeout-minutes: 10
-  #       shell: bash
-  #       run: |
-  #         . venv/bin/activate
-  #         python --version
+  pytest:
+    runs-on: ubuntu-22.04
+    if: |
+      (github.event_name != 'push' || github.event.repository.full_name == 'home-assistant/core')
+      && github.event.inputs.lint-only != 'true'
+      && (needs.info.outputs.test_full_suite == 'true' || needs.info.outputs.tests_glob)
+    needs:
+      - info
+      - gen-requirements-all
+      - hassfest
+      - lint-black
+      - lint-other
+      - lint-isort
+      - mypy
+      - prepare-tests
+    strategy:
+      fail-fast: false
+      matrix:
+        group: ${{ fromJson(needs.info.outputs.test_groups) }}
+        python-version: ["3.9", "3.10"]
+    name: >-
+      Run tests Python ${{ matrix.python-version }} (${{ matrix.group }})
+    container: homeassistant/ci-azure:${{ matrix.python-version }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.0.2
+      - name: Restore full Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v3.0.4
+        with:
+          path: venv
+          key: ${{ runner.os }}-${{ matrix.python-version }}-${{
+            needs.info.outputs.python_cache_key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Register Python problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/python.json"
+      - name: Install Pytest Annotation plugin
+        run: |
+          . venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures==0.1.3
+      - name: Register pytest slow test problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/pytest-slow.json"
+      - name: Run pytest (fully)
+        if: needs.info.outputs.test_full_suite == 'true'
+        timeout-minutes: 60
+        run: |
+          . venv/bin/activate
+          python --version
+          python3 -X dev -m pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            -n auto \
+            --dist=loadfile \
+            --test-group-count ${{ needs.info.outputs.test_group_count }} \
+            --test-group=${{ matrix.group }} \
+            --cov="homeassistant" \
+            --cov-report=xml \
+            -o console_output_style=count \
+            -p no:sugar \
+            tests
+      - name: Run pytest (partially)
+        if: needs.info.outputs.test_full_suite == 'false'
+        timeout-minutes: 10
+        shell: bash
+        run: |
+          . venv/bin/activate
+          python --version
 
-  #         if [[ ! -f "tests/components/${{ matrix.group }}/__init__.py" ]]; then
-  #           echo "::error:: missing file tests/components/${{ matrix.group }}/__init__.py"
-  #           exit 1
-  #         fi
+          if [[ ! -f "tests/components/${{ matrix.group }}/__init__.py" ]]; then
+            echo "::error:: missing file tests/components/${{ matrix.group }}/__init__.py"
+            exit 1
+          fi
 
-  #         python3 -X dev -m pytest \
-  #           -qq \
-  #           --timeout=9 \
-  #           --durations=10 \
-  #           -n 0 \
-  #           --cov="homeassistant.components.${{ matrix.group }}" \
-  #           --cov-report=xml \
-  #           --cov-report=term-missing \
-  #           -o console_output_style=count \
-  #           --durations=0 \
-  #           --durations-min=1 \
-  #           -p no:sugar \
-  #           tests/components/${{ matrix.group }}
-  #     - name: Upload coverage artifact
-  #       uses: actions/upload-artifact@v3.1.0
-  #       with:
-  #         name: coverage-${{ matrix.python-version }}-${{ matrix.group }}
-  #         path: coverage.xml
-  #     - name: Check dirty
-  #       run: |
-  #         ./script/check_dirty
+          python3 -X dev -m pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            -n 0 \
+            --cov="homeassistant.components.${{ matrix.group }}" \
+            --cov-report=xml \
+            --cov-report=term-missing \
+            -o console_output_style=count \
+            --durations=0 \
+            --durations-min=1 \
+            -p no:sugar \
+            tests/components/${{ matrix.group }}
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: coverage-${{ matrix.python-version }}-${{ matrix.group }}
+          path: coverage.xml
+      - name: Check dirty
+        run: |
+          ./script/check_dirty
 
   # coverage:
   #   name: Upload test coverage to Codecov
